version: 2
jobs:
  deploy:
    working_directory: /home/circleci/camsaul/camsaul.com
    docker:
      - image: camsaul/camsaul.com-docker
    steps:
      - restore_cache:
          keys:
            - source-{{ .Branch }}-{{ .Revision }}
            - source-{{ .Branch }}-
            - source-
      - checkout
      - save_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
          paths:
            - .git
      - run: bundle install
      - restore_cache:
          keys:
            - site-{{ .Branch }}-{{ .Revision }}
            - site-{{ .Branch }}-
            - site-
      - run:
          name: Build website
          command: bundle exec jekyll build --incremental
      - save_cache:
          key: site-{{ .Branch }}-{{ .Revision }}
          paths:
            - _site
            - .sass-cache
      - run:
          name: Upload website
          command: aws s3 sync _site s3://camsaul.com/
      - run:
          name: Invalidate Cached Pages
          command: >
            aws configure set preview.cloudfront true &&
            aws cloudfront create-invalidation --distribution-id $CDN_DISTRIBUTION_ID --paths / /index.html /feed.xml
      - run:
          name: Ping Google
          command: curl http://www.google.com/ping?sitemap=https://camsaul.com/feed.xml
workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
